### ISSUE TITLE
[BUG] - System crash/ freeze entirely when starting adaptive mode(need to force close the laptop holding down the power button).

### ISSUE THREAD

**Issue by dutch45612** [JamesCJ60/Universal-x86-Tuning-Utility#71]
**Describe the bug**
System crash/ freeze entirely when starting adaptive mode(need to force close the laptop holding down the power button).

  * While the system is still up, the GPU stays at the minimum value you settle, even if it requires a higher clock to maintain the framerate, stays at minimum 100% load without raising.

**To Reproduce**
Start adaptive mode with a minimum GPU to any value, it happens randomly within about 2 minutes.

**Expected behaviour**
Automatically managing TDP/ Gpu-CPU clock frequency according to load.

**Screenshots**
Black screen, the sound is still working but everything else(including inputs) are frozen.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2

**Additional context**
- My device : GPD WIN MAX 2
- AMD Ryzen 7 6800U with Radeon Graphics (680m)
- RAM 32.0 GB

**Comment by igornovitzky** [comment]
I get this too on 6850u lenovo z13 32gb RAM and Radeon graphics, latest windows 11

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: dutch45612 ***@***.***>
Sent: Wednesday, May 17, 2023 1:25:37 PM
To: JamesCJ60/Universal-x86-Tuning-Utility ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JamesCJ60/Universal-x86-Tuning-Utility] [BUG] (Issue #71)


Describe the bug
System crash/ freeze entirely when starting adaptive mode(need to force close the laptop holding down the power button).

To Reproduce
Start adaptive mode with a minimum GPU to any value, it happens randomly within about 2 minutes.

Expected behaviour
Automatically managing TDP/ Gpu-CPU clock frequency according to load.

Screenshots
Black screen, the sound are still working but everything else(including inputs) are frozen.

Desktop (please complete the following information):

  *   OS Version: Windows 11 22H2

Additional context

  *   My device : GPD WIN MAX 2
  *   AMD Ryzen 7 6800U with Radeon Graphics (680m)
  *   RAM 32.0 GB

**Comment by Tygr09** [comment]
I got that as well.  Lenovo amd ryzen 7 6800 with 3070 graphics and windows 11.  My laptop crashed within 2 minutes.

**Comment by filminghub** [comment]
> I got that as well. Lenovo amd ryzen 7 6800 with 3070 graphics and windows 11. My laptop crashed within 2 minutes.

I have the same specs except I'm using Asus laptop. And I got crashed by turning on performance mode. Do you still have the same issue?

**Comment by igornovitzky** [comment]
My 6850u Lenovo Z13 AMD crashes after 3-4min of performance mode
Igor

**Comment by JamesCJ60** [comment]
Hi, this should no longer be an issue as of the latest betas.
